---
- hosts: router
  connection: local
  gather_facts: no
  tasks:
  - name: check connectivity
    ios_command:
     commands: ping {{item}}
     timeout: 3
     retries: 1
     wait_for: result[0] contains "!!!"
     provider: "{{cli}}"
    with_items: "{{loopback}}"
    ignore_errors: yes
